### ISSUE TITLE
cdp.page.DomContentEventFired event listener not catching an event

### ISSUE THREAD

**Issue by TurboKach** [HMaker/python-cdp#6]
`async with target_session.wait_for(cdp.page.DomContentEventFired):` does not catch an event on tab navigation using a python types generated by `cdpgen`. 
last used protocol commit: https://github.com/ChromeDevTools/devtools-protocol/commit/5caaeb998f6002a68345320ad4d85fbc6afca202
but seems like this bug came a few commits before. 

using a README.md example code:
```
import asyncio
# from pycdp import cdp  # here is an import from default pycdp types
import cdp  # here we imported cdp which was generated by cdpgen
from pycdp.browser import ChromeLauncher
from pycdp.asyncio import connect_cdp

async def main():
    chrome = ChromeLauncher(
        binary='/usr/bin/google-chrome', # linux path
        args=['--remote-debugging-port=9222', '--incognito']
    )
    # ChromeLauncher.launch() is blocking, run it on a background thread
    await asyncio.get_running_loop().run_in_executor(None, chrome.launch)
    conn = await connect_cdp('http://localhost:9222')
    target_id = await conn.execute(cdp.target.create_target('about:blank'))
    target_session = await conn.connect_session(target_id)
    await target_session.execute(cdp.page.enable())
    await target_session.execute(cdp.page.navigate('https://chromedevtools.github.io/devtools-protocol/'))
    # you may use "async for target_session.listen()" to listen multiple events, here we listen just a single event.
    async with target_session.wait_for(cdp.page.DomContentEventFired):
        dom = await target_session.execute(cdp.dom.get_document())
        node = await target_session.execute(cdp.dom.query_selector(dom.node_id, 'p'))
        js_node = await target_session.execute(cdp.dom.resolve_node(node))
        print((await target_session.execute(cdp.runtime.call_function_on('function() {return this.innerText;}', js_node.object_id, return_by_value=True)))[0].value)
    await target_session.execute(cdp.page.close())
    await conn.close()
    await asyncio.get_running_loop().run_in_executor(None, chrome.kill)

asyncio.run(main())
```

**Comment by HMaker** [comment]
It's probably caused by race conditions, the page might be loading too fast between the `cdp.page.navigate()` command and the `async with target_session.wait_for()` subscription. We need to subscribe to the event before it be triggered.

**Comment by HMaker** [comment]
test again with latest version

**Comment by TurboKach** [comment]
seems working. 
will check it later also on a more complex code.

**Comment by HMaker** [comment]
I tried to reproduce with your steps but `cdp.page.DomContentEventFired` is still fired. You don't need to generate a new cdp package, you can refresh the builtin ones
1. Clone this repository
2. Replace the `browser_protocol.json` and `js_protocol.json` files at `pycdp/gen` folder by the CDP protocol version you wish, then run `python pycdp/gen/generate.py`, it will refresh builtin `cdp` wrapper.
3. Run your test script again.

**Comment by TurboKach** [comment]
Here was a cdpgen-generated package misunderstood. 
cdpgen generated package cannot be used separate from pycpd due to being a part of it. 

https://github.com/HMaker/python-cdp/pull/4
