### ISSUE TITLE
Add to_json method to CDP events

### ISSUE THREAD

**Issue by RazorBest** [HMaker/python-cdp#9]
Hi,

All the python classes have the `from_json` method. The ones that represent CDP data types also have a `to_json` method, but the events don't have. I would like a complete coverage of json conversion for the python objects. [I think the generation script can be modified to achieve this requirement](https://github.com/HMaker/python-cdp/blob/6ce129024f36445855ee88339969e0de641c12a5/pycdp/gen/generate.py#L718).

At the moment, I don't see this to be a difficult task. I am happy to make the contribution myself.

GG for the project

**Comment by HMaker** [comment]
Have you tried [dataclasses.asdic()][1]?

I suppose the following is enough
```py
def to_json(self):
    return dataclasses.asdict(self)
````

[1]: https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict

**Comment by HMaker** [comment]
What would be the use case for that?

The CDP command types have the `to_json()` method to serialize it to be sent to the chrome browser (on-wire format). The JSON structure matches the defined ones by the CDP protocol specification.

**Comment by razvan-pricop-ptt** [comment]
I understand that, but my use case is a little different. I have a program that uses python-cdp to listen to CDP events, and I want to add functional tests. So, I chose my tests to have as input, CDP events in JSON format, as close as possible to what chrome would give. I don't know a way to access the JSON objects directly, so I chose the following solution: get the CDP events converted to Python objects, as python-cdp does, then convert them back to JSON using the `to_json` methods.

**Comment by RazorBest** [comment]
I understand that, but my use case is a little different. I have a program that uses python-cdp to listen to CDP events, and I want to add functional tests. So, I chose my tests to have as input, CDP events in JSON format, as close as possible to what chrome would give. I don't know a way to access the JSON objects directly, so I chose the following solution: get the CDP events converted to Python objects, as python-cdp does, then convert them back to JSON using the `to_json` methods.

**Comment by HMaker** [comment]
You want to inject fake CDP events and test your listener behavior? Can't you just inject plain JSON objects and let pycdp parse it?

Instead you can make the function which handles CDP events take them as argument, the Python wrapper types. Then you can call it directly from the test.

Anyway feel free to make a PR, I will review it. Make the `to_json()` follow the same syntax and semantic of CDP.
